# Generated by Django 5.1.5 on 2025-05-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0003_auto_20250528_0557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='resenna',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='resenna',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='TipoEmpleado',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Resenna',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
