# Generated by Django 5.2.1 on 2025-06-04 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('productos', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'DETALLEPEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'db_table': 'EMPLEADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'METODOPAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'NOTIFICACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.CharField(max_length=255)),
                ('disponible', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resenna',
            fields=[
                ('id_resenna', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('valoracion', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'RESENNA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ubicacion_detalle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'STOCK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPOEMPLEADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasenna', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=9)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_token_expira', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador'), ('admin', 'Administrador')], default='cliente', max_length=20)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField()),
                ('ubicacion_detalle', models.CharField(max_length=255)),
                ('fecha_alerta', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido_aprobado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
        ),
    ]
