# Generated by Django 6.0.5 on 2026-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('peluche', 'Peluche'), ('botella', 'Botella'), ('termo', 'Termo'), ('pin', 'Pin'), ('llavero', 'Llavero'), ('lampara', 'Lámpara')], default='peluche', max_length=20),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='PRODUCTO',
        ),
    ]
