# Generated by Django 6.0.5 on 2026-05-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
