# Generated by Django 6.0.5 on 2026-05-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resenna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoempleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
