# Generated by Django 5.2.1 on 2025-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
