# Generated by Django 5.2.1 on 2025-05-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='resenna',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='resenna',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='TipoEmpleado',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Resenna',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
