# Generated by Django 5.2.1 on 2025-05-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resenna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoempleado',
            options={'managed': False},
        ),
    ]
