# Generated by Django 5.2.1 on 2025-05-31 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_carrito_table_alter_detallepedido_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='CARRITO',
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='DETALLEPEDIDO',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='EMPLEADO',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='METODOPAGO',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='NOTIFICACION',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='PAGO',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='PEDIDO',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='PRODUCTO',
        ),
        migrations.AlterModelTable(
            name='resenna',
            table='RESENNA',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='STOCK',
        ),
        migrations.AlterModelTable(
            name='tipoempleado',
            table='TIPOEMPLEADO',
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField()),
                ('ubicacion_detalle', models.CharField(max_length=255)),
                ('fecha_alerta', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
        ),
    ]
